### ISSUE TITLE
The ui app.css 404

### ISSUE THREAD

**Issue by seepine** [iron-io/functions-ui#20]
![image](https://github.com/iron-io/functions-ui/assets/93666053/95013bae-e210-448c-b561-2bf5fff3cac7)

![image](https://github.com/iron-io/functions-ui/assets/93666053/a07b7ef4-d965-417e-99e6-490497ed367d)

```yml
version: '3'
services:
  api:
    image: iron/functions
    volumes:
      - api_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080

  ui:
    image: iron/functions-ui
    environment:
      API_URL: http://api:8080
    ports:
      - 4000:4000

volumes:
    api_data:
```
